# Generated by Django 5.2.8 on 2025-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photo file', null=True, upload_to='person/'),
        ),
    ]
