# Generated by Django 5.2.8 on 2025-11-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teammember_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.CharField(blank=True, default='default.png', help_text="Relative path under main/static/images/ (e.g., 'person/john.webp')", max_length=255),
            preserve_default=False,
        ),
    ]
