# Generated by Django 5.2.8 on 2025-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_servicecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='link_text',
            field=models.CharField(blank=True, help_text="Optional button text (e.g., 'Learn More')", max_length=50),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional external URL for the card button'),
        ),
    ]
