# Generated by Django 5.2.8 on 2025-11-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_servicecard_link_text_servicecard_link_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecard',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Card', 'verbose_name_plural': 'News Cards'},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='github_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='twitter_url',
            new_name='instagram_url',
        ),
    ]
