# Generated by Django 5.2.8 on 2025-12-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_forgotpasswordtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('Head of Department', 'Head of Department'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer')], max_length=50)),
                ('photo', models.CharField(blank=True, help_text="Relative path under main/static/images/faculty/ (e.g., 'faculty/jebrankhan.jpeg')", max_length=255)),
                ('research_area_1', models.CharField(blank=True, help_text='First research area', max_length=100)),
                ('research_area_2', models.CharField(blank=True, help_text='Second research area', max_length=100)),
                ('research_area_3', models.CharField(blank=True, help_text='Third research area', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('website_url', models.URLField(blank=True, help_text='Personal/research website URL')),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('order', models.IntegerField(default=0, help_text='Display order on the page (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
