# Generated by Django 5.2.8 on 2025-12-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_forgotpasswordtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(default='Professor', max_length=255)),
                ('picture', models.ImageField(upload_to='static\\images\\professor image/')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('specialization_1', models.CharField(blank=True, max_length=255)),
                ('specialization_2', models.CharField(blank=True, max_length=255)),
                ('specialization_3', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
