# Generated by Django 5.2.8 on 2025-12-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_faculty'),
        ('main', '0010_professor'),
    ]

    operations = [
    ]
