# Generated by Django 5.2.8 on 2025-12-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_0010_faculty_0010_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_area_1',
            field=models.TextField(blank=True, help_text='First research area'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_area_2',
            field=models.TextField(blank=True, help_text='Second research area'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_area_3',
            field=models.TextField(blank=True, help_text='Third research area'),
        ),
    ]
