# Generated by Django 5.2.8 on 2025-12-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_professor_alter_faculty_research_area_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Bootstrap Icon class name (e.g., 'bi-cpu' for CPU icon)", max_length=100)),
                ('link_url', models.URLField(blank=True, help_text="URL for the 'Explore Club' button (e.g., 'aipc.html' or external URL)")),
                ('link_text', models.CharField(default='Explore Club', help_text='Button text', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order on the page (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['order', 'name'],
            },
        ),
    ]
