# Generated by Django 5.2.8 on 2025-12-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_club'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPasswordToken',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='research_area_1',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='research_area_2',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='research_area_3',
        ),
    ]
