# Generated by Django 5.2.8 on 2025-12-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_forgotpasswordtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='research_area',
            field=models.TextField(blank=True, help_text='Research areas the faculty member is working on'),
        ),
    ]
