# Generated by Django 5.2.8 on 2025-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_faculty_research_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='research_area_2',
            field=models.TextField(blank=True, help_text='Additional research area'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_area_3',
            field=models.TextField(blank=True, help_text='Additional research area'),
        ),
    ]
