# Generated by Django 4.2.24 on 2026-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_faculty_research_area_2_faculty_research_area_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/'),
        ),
    ]
